databases:
  - name: snippetdb
    plan: free
    databaseName: snippetdb
    user: snippetuser

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'cd src && python -m gunicorn snippet-manager.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snippetdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4