databases:
  - name: snippet_manager_db
    plan: free
    databaseName: snippet_manager_db
    user: snippetuser

services:
  - type: web
    plan: free
    name: snippet_manager
    runtime: python
    dockerfilePath: ./Dockerfile
#    buildCommand: './build.sh'
#    startCommand: 'cd src && python -m gunicorn snippet_manager.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snippet_manager_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: STATIC_ROOT
        value: "/opt/render/project/src/staticfiles"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: DJANGO_SETTINGS_MODULE
        value: "snippet_manager.settings"
